# Generated by Django 5.1.3 on 2024-12-27 14:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='html',
            options={'verbose_name': 'Html', 'verbose_name_plural': 'Htmls'},
        ),
        migrations.AlterField(
            model_name='html',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents'),
        ),
    ]
