# Generated by Django 5.1.4 on 2025-01-07 08:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_html_options_alter_html_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='cms_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_logo', models.FileField(null=True, upload_to='images/')),
                ('existing_logo_title', models.TextField(blank=True, null=True)),
                ('footer_logo', models.FileField(null=True, upload_to='images/')),
                ('existing_favicon', models.FileField(null=True, upload_to='images/')),
                ('status', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cms_setting',
                'verbose_name_plural': 'Cms_setting',
            },
        ),
        migrations.AlterField(
            model_name='html',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
