# Generated by Django 5.1.4 on 2025-01-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_cms_setting_alter_html_contents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cms_setting',
            options={'verbose_name': 'Cms_setting', 'verbose_name_plural': 'Cms_settings'},
        ),
    ]
