# Generated by Django 5.1.4 on 2025-01-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_cms_setting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_setting',
            name='analytic_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='analytic_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='fapp_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='fpixel_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='gmail_client_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='gmail_redirect_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='gmail_secret_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='recapcha_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='secret_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='site_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='social_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cms_setting',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
