# Generated by Django 5.1.4 on 2025-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_cms_setting_analytic_allow_cms_setting_analytic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_setting',
            name='analytic_allow',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='fpixel_allow',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='recapcha_allow',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='social_allow',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
