# Generated by Django 5.1.4 on 2025-01-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_cms_setting_analytic_allow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_setting',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
