# Generated by Django 5.1.4 on 2025-01-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_cms_setting_existing_logo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_setting',
            name='existing_favicon',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='existing_logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='footer_logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
