# Generated by Django 5.1.4 on 2025-02-24 09:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_cms_setting_existing_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField()),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_keyword', models.TextField()),
                ('meta_desc', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='html',
            options={},
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='analytic_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='existing_favicon',
            field=models.FileField(default='images/default_logo.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='existing_logo',
            field=models.FileField(default='images/default_logo.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='footer_logo',
            field=models.FileField(default='images/default_logo.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='recapcha_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='social_allow',
            field=models.IntegerField(default=0),
        ),
    ]
