# Generated by Django 5.1.4 on 2025-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_pages_alter_html_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='js',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='meta_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='meta_keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
