# Generated by Django 5.1.4 on 2025-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_pages_css_alter_pages_js_alter_pages_meta_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
