# Generated by Django 5.1.4 on 2025-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_navigroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigroupspages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='navigroups',
            name='end_image',
            field=models.FileField(default='images/default_logo.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='navigroups',
            name='external_link',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroups',
            name='link_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroups',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroups',
            name='page_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroups',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroups',
            name='start_image',
            field=models.FileField(default='images/default_logo.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='navigroups',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
