# Generated by Django 5.1.4 on 2025-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_navigroupspages_navigroups_end_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigroups',
            name='end_image',
        ),
        migrations.RemoveField(
            model_name='navigroups',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='navigroups',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='navigroups',
            name='order',
        ),
        migrations.RemoveField(
            model_name='navigroups',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='navigroups',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='navigroups',
            name='start_image',
        ),
        migrations.RemoveField(
            model_name='navigroups',
            name='target',
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='end_image',
            field=models.FileField(default='images/default_logo.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='external_link',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='link_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='page_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='start_image',
            field=models.FileField(default='images/default_logo.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
