# Generated by Django 5.1.4 on 2025-02-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_navigroups_end_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigroupspages',
            name='code',
        ),
    ]
