# Generated by Django 5.1.4 on 2025-02-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_navigroupspages_navi_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigroupspages',
            name='navi_code',
        ),
    ]
