# Generated by Django 5.1.4 on 2025-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_navigroupspages_navi_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigroupspages',
            name='navi_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
