# Generated by Django 5.1.4 on 2025-02-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_navigroupspages_navi_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='external_link',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='link_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='page_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
