# Generated by Django 5.1.4 on 2025-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_navigroupspages_external_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='external_link',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='link_type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='page_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='target',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
