# Generated by Django 5.1.4 on 2025-02-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_navigroupspages_external_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='external_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
