# Generated by Django 5.1.4 on 2025-03-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_navigroupspages_external_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigroupspages',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='navigroups',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='navi_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='backend.navigroups'),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.navigroupspages'),
        ),
    ]
