# Generated by Django 5.1.4 on 2025-03-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_navigroupspages_options_alter_navigroups_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='parent_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.navigroupspages'),
        ),
    ]
