# Generated by Django 5.1.4 on 2025-03-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_navigroupspages_parent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigroupspages',
            options={},
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='navi_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='backend.navigroups'),
        ),
        migrations.AlterField(
            model_name='navigroupspages',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
