# Generated by Django 5.1.4 on 2025-03-12 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_navigroupspages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigroupspages',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='navigroupspages',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.navigroupspages'),
        ),
    ]
