# Generated by Django 5.1.4 on 2025-03-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_navigroupspages_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='backend.navigroupspages'),
        ),
    ]
