# Generated by Django 5.1.4 on 2025-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_navigroupspages_page_id_navigroupspages_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
