# Generated by Django 5.1.4 on 2025-03-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_navigroupspages_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_pages', to='backend.pages'),
        ),
    ]
