# Generated by Django 5.1.4 on 2025-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_navigroupspages_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
