# Generated by Django 5.1.4 on 2025-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_pages_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='fpixel_allow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cms_setting',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
