# Generated by Django 5.1.4 on 2025-04-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
