# Generated by Django 5.1.4 on 2025-04-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contents',
        ),
    ]
