# Generated by Django 5.1.4 on 2025-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
