# Generated by Django 5.1.4 on 2025-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_alter_comment_created_at_alter_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
