# Generated by Django 5.1.4 on 2025-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_html_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigroups',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigroupspages',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
