# Generated by Django 5.1.4 on 2025-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_navigroups_status_navigroupspages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigroupspages',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
