# Generated by Django 5.1.4 on 2025-04-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_permission_role_customuser_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
