# Generated by Django 5.1.3 on 2025-05-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_alter_post_likes_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='navigroups',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
