# Generated by Django 5.1.3 on 2025-05-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_post_post_header_image_alter_navigroups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
