# Generated by Django 5.1.3 on 2025-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_pages_page_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
