# Generated by Django 5.1.3 on 2025-05-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='message',
            new_name='contents',
        ),
    ]
