# Generated by Django 5.1.3 on 2025-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
