# Generated by Django 5.1.3 on 2025-06-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigroupspages',
            name='page_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
