# Generated by Django 5.1.4 on 2025-03-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Html',
        ),
    ]
